[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tikworks"
version = "0.1.0"
description = "Tikworks core tools"
authors = [{name = "Arda Kutlu", email = "ardakutlu@gmail.com"}]
requires-python = "> 3.10"
readme = "README.md"

[tool.setuptools]
package-dir = {"" = "src/python"}
packages = { find = {} }

[tool.black]
line-length = 88
target-version = ["py310"]
extend-exclude = "vendor"

[tool.isort]
profile = "black"
known_first_party = ["tik"]
skip_glob = ["*/vendor/*"]
