"""DCC-agnostic core of tik.trigger.

Nothing in this package imports Maya or Qt.
"""

from tik.core.fields import (
    BoolField,
    ChoiceField,
    DictField,
    Field,
    FieldGroup,
    FileField,
    FloatField,
    IntField,
    ListField,
    NodeRefField,
    StringField,
    Vector2Field,
    Vector3Field,
    VectorField,
)
from tik.core.side import Side

from . import versioning
from .action import Action, ActionContext
from .document import ActionNode, Document
from .events import ERROR, LOG, PROGRESS, EventBus
from .exceptions import (
    ActionError,
    ActionExecutionError,
    AttachError,
    BuildError,
    DuplicateRegistrationError,
    FieldValidationError,
    GuideError,
    ModuleError,
    NotFoundError,
    RegistryError,
    SessionError,
    SessionLoadError,
    SessionSaveError,
    TriggerError,
)
from .manifest import GuideAttr, GuideLayout, Input, instance_key
from .module import Module
from .registry import (
    clear_registries,
    get_action,
    get_module,
    is_action_registered,
    is_module_registered,
    iter_actions,
    iter_modules,
    list_actions,
    list_modules,
    register_action,
    register_module,
    unregister_action,
    unregister_module,
)
from .schemas import (
    AFTERLIFE_MODES,
    SCHEMA_VERSION,
    ActionInstance,
    GuidePose,
    ModuleInstance,
    ParentRef,
    RigDocument,
    order_instances,
    split_source,
)

__all__ = [
    "Action",
    "ActionContext",
    "ActionNode",
    "Document",
    "versioning",
    "EventBus",
    "PROGRESS",
    "LOG",
    "ERROR",
    "GuideAttr",
    "GuideLayout",
    "Input",
    "instance_key",
    "Module",
    "Side",
    "Field",
    "FileField",
    "DictField",
    "IntField",
    "FieldGroup",
    "FloatField",
    "BoolField",
    "StringField",
    "ChoiceField",
    "Vector2Field",
    "Vector3Field",
    "VectorField",
    "ListField",
    "NodeRefField",
    "register_action",
    "register_module",
    "get_action",
    "get_module",
    "list_actions",
    "list_modules",
    "iter_actions",
    "iter_modules",
    "is_action_registered",
    "is_module_registered",
    "unregister_action",
    "unregister_module",
    "clear_registries",
    "SCHEMA_VERSION",
    "AFTERLIFE_MODES",
    "GuidePose",
    "ParentRef",
    "ModuleInstance",
    "ActionInstance",
    "RigDocument",
    "order_instances",
    "split_source",
    "TriggerError",
    "RegistryError",
    "DuplicateRegistrationError",
    "NotFoundError",
    "SessionError",
    "SessionLoadError",
    "SessionSaveError",
    "ModuleError",
    "GuideError",
    "BuildError",
    "AttachError",
    "ActionError",
    "ActionExecutionError",
    "FieldValidationError",
]
