"""Sphinx configuration for the TikWorks documentation.

Build locally from the ``docs`` folder with ``make html`` (see
``docs/requirements.txt`` for the packages). The API reference is generated by
sphinx-autoapi straight from ``src/python/tik``; nothing under ``autoapi/`` is
checked in.
"""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# -- Project information -----------------------------------------------------

project = "TikWorks"
copyright = "2025-2026, Arda Kutlu"
author = "Arda Kutlu"
release = (REPO_ROOT / "VERSION").read_text(encoding="utf-8").strip() or "0.0.0"
version = release

# -- General configuration ---------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    # Google-style Args:/Returns:/Raises: sections are the house docstring
    # style (AI/documentation_rules.md).
    "sphinx.ext.napoleon",
    "autoapi.extension",
    "sphinx_design",
    "sphinx_copybutton",
]

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

# Napoleon: render ``Attributes:`` sections as ``:ivar:`` fields. The default
# emits an ``.. attribute::`` directive per line, which duplicates the
# attribute autoapi documents itself and produced a "duplicate object
# description" warning for every dataclass field in the codebase.
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_use_ivar = True
napoleon_use_param = True
napoleon_use_rtype = True

# -- sphinx-autoapi ----------------------------------------------------------

# One tree, rooted at the package itself. Listing sub-packages as well would
# document them twice, under both their real dotted path and a truncated one.
autoapi_dirs = [str(REPO_ROOT / "src" / "python" / "tik")]
autoapi_type = "python"
autoapi_root = "autoapi"
autoapi_ignore = [
    "*setup*",
    "*shiboken*",
    "*PySide2*",
    "*PySide6*",
    "*PyQt5*",
    "*PyQt6*",
    "*external/**/*",
    # Third-party code shipped with the repository (the Qt.py shim and
    # apiundo) is not TikWorks API.
    "*/tik/vendor/*",
]
autoapi_file_patterns = ["*.py"]
autoapi_member_order = "groupwise"
# Module and action folders (``modules/arm/arm.py``) have no ``__init__.py``.
autoapi_python_use_implicit_namespaces = True
autoapi_add_toctree_entry = True
# ``imported-members`` is deliberately absent: with it, every name re-exported
# from ``tik.maya`` (``Transform``, ``Node``, ``resolve``...) is documented
# twice and every ``:class:`` reference to it becomes ambiguous.
autoapi_options = [
    "members",
    "undoc-members",
    "show-inheritance",
    "show-module-summary",
]
autodoc_typehints = "signature"
add_module_names = False

# autoapi resolves imports statically. It cannot follow the vendored Qt.py
# shim (it builds its submodules at runtime) nor ``from tik.maya import
# attribute`` (a submodule re-exported as an attribute). Both are correct
# Python and neither affects the generated pages, so the warning is noise.
suppress_warnings = ["autoapi.python_import_resolution"]

# -- sphinx-copybutton -------------------------------------------------------

copybutton_prompt_text = r">>> |\.\.\. |\$ "
copybutton_prompt_is_regexp = True

# -- Options for HTML output -------------------------------------------------

html_theme = "furo"
html_title = f"TikWorks {release}"
html_logo = "_static/logo.png"
html_static_path = ["_static"]
html_css_files = ["custom.css"]
html_theme_options = {
    "sidebar_hide_name": False,
    "light_css_variables": {
        "color-brand-primary": "#d95f00",
        "color-brand-content": "#d95f00",
    },
    "dark_css_variables": {
        "color-brand-primary": "#FE7E00",
        "color-brand-content": "#FE9500",
    },
}

exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
